#!/bin/bash

# libjpeg-turbo Style Checker, or
# How I Learned to Stop Worrying and Love Regular Expressions
#
# Copyright (C)2018-2026 D. R. Commander.  All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# - Neither the name of the libjpeg-turbo Project nor the names of its
#   contributors may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS",
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

SCRIPTDIR=`dirname $0`

set -f

# Move along.  Nothing to format here.
FILES='./* :!.gitattributes :!doc/ :!*.ppm :!*.pgm :!*.bmp :!*.icc'

# Files that use tabs for indentation
TIFILES='release/ test/'
NTIFILES=$(for i in $TIFILES; do echo :!$i; done)

# C, Java, and GAS files
CGFILES='*.c *.h'
NCGFILES=':!*.c :!*.h'
CJGFILES="$CGFILES"' *.java'
NCJGFILES="$NCGFILES"' :!*.java'

if [ "$1" = "-selftest" ]; then
	pushd $SCRIPTDIR >/dev/null 2>&1
	SCRIPTDIR=.
	FILES="styletest.c"
	CGFILES="styletest.c"
	CJGFILES="styletest.c"
	TIFILES=
elif [ $# -gt 0 ]; then
	FILES=${1+"$@"}
	CGFILES=${1+"$@"}
	CJGFILES=${1+"$@"}
	TIFILES=
fi

filter_quotes()
{
	pcregrep -v ':.*\"[^\"]*'"$EXPR"'[^\"]*\"'
}

grep_without_c_comments()
{
	git ls-files -- ${2+"$@"} | while read file; do
		"$SCRIPTDIR/remcomms.sh" $file | pcregrep "$1" | sed -E 's@^@'$file':@'
	done
}


echo

echo '********** DETECTING WHITESPACE ERRORS **********'

echo '---------- Stray tab characters ----------'
echo
git grep -E $'\t' -- $FILES $NTIFILES
if [ "$TIFILES" != "" ]; then
	git grep -P '[^^\n\t]\t' -- $TIFILES
fi
echo

echo "---------- Spaces used for indentation where they shouldn't be ----------"
echo
EXPR='^ +'
if [ "$TIFILES" != "" ]; then
	git grep -E "$EXPR" $TIFILES
fi
unset EXPR
echo

echo '---------- Alt-Space ----------'
echo
git grep ' ' -- $FILES
echo

echo '---------- Blank line(s) at top of file ----------'
echo
git ls-files -- $FILES | while read file; do
	MATCH=`head -n1 $file | grep -E '^[ '$'\t]*$'`
	if [ $? = 0 ]; then
		echo $file:$MATCH
	fi
done
echo

echo '---------- No blank line at end of file ----------'
echo
git ls-files -- $FILES | while read file; do
	pcregrep -ML '\n\Z$' $file
done
echo

echo '---------- General whitespace errors ----------'
echo
git diff --check $(git rev-list HEAD | tail -n 1) -- $FILES
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT COMMENT FORMATTING **********'

echo '---------- C++-style comments in C files ----------'
echo
git grep -P '(?<!http:)(?<!https:)(?<!ftp:)//' -- $FILES ':!*.java' ':!test/'
echo

echo '---------- C-style trailing comments in Java files ----------'
echo
git grep -E '[^ ] +\/\*' -- org *.java
echo

echo # ************************************************************************


echo '********** DETECTING BAD LINE CONTINUATION SPACING **********'
echo
git grep -E '[^ ]+(\\| {2,}\\)$' -- $FILES
echo

echo # ************************************************************************


echo '********** DETECTING UNATTACHED else/catch/struct **********'
echo
git ls-files -- $FILES | while read file; do
	pcregrep -H -M '^[^{]*}\n+ *(else|catch)' $file
	pcregrep -H -M '[^#]else\n *{' $file
	pcregrep -H -M '^[^\n\(\/\*]*struct[^\n\)\/\*]*\n[ ]*\{[^\};]*$' $file
done
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT BRACKET SPACING **********'

echo '---------- Function-like macro with unattached bracket ----------'
echo
git grep -E '^ *\{[^\}]*\\$' -- $FILES
echo

echo '---------- {something ----------'
echo
EXPR='{[^ \}]'
EXCLEXPR='(?!{@link)(?!{@code)'
git grep -P "$EXCLEXPR""$EXPR" -- $FILES ':!BUILDING.md' ':!ChangeLog.md' ':!*CMakeLists.txt' ':!cmakescripts/' ':!test/' |
	filter_quotes
unset EXPR
unset EXCLEXPR
echo

echo '---------- { something; ... ----------'
echo
EXPR='{ [^}]*[;\(][^}\)]*$'
git grep -P "$EXPR" -- $FILES
unset EXPR
echo

echo '---------- something} ----------'
echo
EXPR='[^ \{@]}'
git grep -P "$EXPR" -- $FILES ':!BUILDING.md' ':!ChangeLog.md' ':!*CMakeLists.txt' ':!cmakescripts/' ':!README.md' ':!test/' |
	grep -vE '\.java: +\* +.*'"$EXPR" |
	filter_quotes
unset EXPR
echo

echo '---------- ... something } ----------'
echo
EXPR='^[^{]*[^ \}] +}'
git grep -E "$EXPR" -- $FILES
unset EXPR
echo

echo '---------- something{ ----------'
echo
EXPR='[^ @]{'
EXCLEXPR='(?![\.(>]{@link)'
git grep -P "$EXCLEXPR""$EXPR" -- $FILES ':!BUILDING.md' ':!*CMakeLists.txt' ':!cmakescripts/' ':!README.md' ':!test/'
unset EXPR
unset EXCLEXPR
echo

echo '---------- }something ----------'
echo
EXPR='}[^ ;,\)\.\(\[\<\]\"]'
git grep -P "$EXPR" -- $FILES ':!BUILDING.md' ':!ChangeLog.md' ':!*CMakeLists.txt' ':!cmakescripts/' ':!README.md' ':!test/'
unset EXPR
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT STATEMENT SPACING **********'

echo '---------- if( ----------'
echo
git grep -P '(?<!_g)if\(' -- $FILES ':!*CMakeLists.txt' ':!cmakescripts/'
echo

for statement in for else catch while do switch; do
	echo '---------- '$statement'( ----------'
	echo
	git grep -E $statement'\(' -- $FILES ':!*CMakeLists.txt' ':!cmakescripts/'
	git ls-files -- $FILES | while read file; do
		pcregrep -H -M $statement' *\([^\n]*\n *{' $file
	done
	echo
done

echo '---------- Semicolon spacing ----------'
echo
git grep -P '(?<!;) ;' -- $FILES $NFORMATTED
echo

echo '---------- Semicolon spacing in one-liners ----------'
echo
EXPR='; [^ }/\\]'
EXCLEXPR='(?! *for \()'
grep_without_c_comments '^'"$EXCLEXPR"'.*'"$EXPR" $FILES ':!CMakeLists.txt' ':!cmakescripts/' ':!LICENSE.md' ':!release/' ':!test/' |
	filter_quotes
unset EXPR
unset EXCLEXPR
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT FUNCTION/TYPE CAST SPACING **********'

echo '---------- (type*) ----------'
echo
git grep -E '[^ \(\*]\*\)' -- $FILES ':!cmakescripts/GNUInstallDirs.cmake'
echo

echo '---------- (type**) ----------'
echo
EXPR='[^ \*]\*\*\)'
git grep -E "$EXPR" -- $FILES ':!BUILDING.md' ':!README.md'
unset EXPR
echo

echo '---------- (type) var ----------'
echo
EXPR='(^| |\(|\*)\([^\)\(\> \*]*\) [A-Za-z0-9_\(\"\&][^ \&]'
git grep -P "$EXPR" -- $FILES $NCJGFILES ':!*.md' ':!test/'
# Process C, Java, and GAS files separately, so we can filter out the comments
EXCLEXPR='(?<!if)'
grep_without_c_comments "$EXCLEXPR""$EXPR" $CJGFILES |
	filter_quotes
unset EXPR
unset EXCLEXPR
echo

echo '---------- (type *) var ----------'
echo
git grep -P '(?<!\ sizeof\(void\ )\*\) [A-Za-z0-9_\(]' -- $FILES ':!BUILDING.md'
echo

echo '---------- (*cinfo->something->method)(args) ----------'
echo
git grep -E '\(\*[^ ]*\)\(' -- $FILES
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT MACRO SPACING **********'
echo
git ls-files -- $FILES | while read file; do
	pcregrep -H -M '#define.*\\\n   [ ]*[^ ]*' $file
done
# #define  something
git grep -E '^[#%]define {2,}' -- $FILES
# #define something(...) something
git grep -E '^[#%]define [A-Za-z0-9_]+\([^\(\)]*\) [^ \\{]' -- $FILES
# #define something something
git grep -E '^[#%]define [^\(\) ]+ [^ \\{/]' -- $FILES ':!org_libjpegturbo_turbojpeg_TJ.h'
# #if defined condition
git grep -E 'defined ' $CGFILES
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT COMMA SPACING **********'

echo '---------- [ ], ----------'
echo
EXPR=' ,'
EXCLEXPR='(?<!,)'
git grep -P "$EXCLEXPR""$EXPR" -- $FILES
unset EXPR
unset EXCLEXPR
echo

echo '---------- ,something ----------'
echo
EXPR=',[^ \)\$\"]'
EXCLEXPR='(?<![\"\[])'
git grep -P "$EXCLEXPR""$EXPR" -- $FILES ':!*CMakeLists.txt'
unset EXPR
unset EXCLEXPR
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT OPERATOR SPACING **********'

echo '---------- Incorrect pointer operator spacing ----------'
echo
EXPR='[^ /]\* '
git grep -E "$EXPR" -- $FILES $NCGFILES ':!BUILDING.md' ':!ChangeLog.md' ':!cmakescripts/' ':!org/scijava/' ':!test/' |
	filter_quotes
# Process C and GAS files separately, so we can parse out the comments
grep_without_c_comments "$EXPR" $CGFILES |
	filter_quotes
unset EXPR
echo

echo '---------- Incorrect address operator spacing ----------'
echo
git grep -E '[^ \&]\& ' -- $FILES
echo

# OPERATORS:
# Assignment: =, +=, -=, *=, /=, %=, &=, |=, ^=, <<=, >>=
# Arithmetic: +, -, *, /, %
# Unary: +something, -something
# Increment/decrement: ++something, something++, --something, something--
# Comparison: ==, !=, >, <, >=, <=
# Logical: !, &&, ||
# Bitwise: ~, &, |, ^, <<, >>

echo '---------- No space before other operators ----------'
echo
OP='([=\+\-\*/%&\|\^\!\<\>]*=|[\+\-\*/%]|\>+|\<+|&+|\|+|\^)'
EXPR='[^ ]\b[\)\]]*'"$OP"
git grep -P "$EXPR" -- $FILES $NCJGFILES ':!*.md' ':!*.yml' ':!CMakeLists.txt' ':!cmakescripts/' ':!MANIFEST.MF' ':!release/' ':!test/'

# Process C, Java, and GAS files separately, so we can filter out the comments
OP='(?!\-\>)(?!\+\+)(?!\-\-)([=\+\-\*/%&\|\^\!\<\>]*=|[\+/%]|\*(?!\))|\-(?![0-9])|\>+|\<+|&&|&|\|+|\^)'
EXPR='[^ ]\b[\)\]]*'"$OP"
EXCLEXPR='(?<!^#error TurboJPEG/)'
grep_without_c_comments "$EXPR""$EXCLEXPR" $CJGFILES ':!org/scijava' |
	filter_quotes |
	pcregrep -v ':#include \<.*\>'

# Process ternary conditional operators separately, so we can filter out
# cases and labels.
EXPR='[^ ]\b[\)\]]*[?:]'
grep_without_c_comments "$EXPR" $CJGFILES |
	filter_quotes |
	grep -vE '(\.c|\.java|\.h): *(case|default|bailout).*:'

unset EXPR
unset EXCLEXPR
echo

echo '---------- No space after other operators ----------'
echo
OP='([=\+\-\*/%&\|\^\!\<\>]*=|[\+\-\*/%]|\>+|\<+|&+|\|+|\^)'
EXPR="$OP"'[\(]*\b[^ ]'
git grep -P "$EXPR" -- $FILES $NCJGFILES ':!*.md' ':!*.yml' ':!CMakeLists.txt' ':!cmakescripts/' ':!MANIFEST.MF' ':!md5/CMakeLists.txt' ':!release/' ':!test/'

# NOTE: We can't check for *something or &something effectively, because
# there's no way to distinguish those errors from valid pointer/address
# operators.  We also can't check for -something effectively, because there's
# no way to distinguish those errors from valid unary operators.  We have to
# hope that, if such errors exist, they will be caught by the something{op}
# check.  We also have to hope that someone will eventually write a decent
# open source C style checker!
OP='([=\+\-\*/%&\|\^\!\<\>]*=|[\+/%]|\>+|\<+|&&|\|+|\^)(?<!\-\>)(?<!\+\+)(?<!\-\-)'
EXPR="$OP"'[\(]*\b[^ ]'
EXCLEXPR='(?<!^#error TurboJPEG/J)'
grep_without_c_comments "$EXPR""$EXCLEXPR" $CJGFILES |
	filter_quotes |
	pcregrep -v ':#include \<.*\>'

# Process ternary conditional operators separately
EXPR='[?:][\(]*\b[^ ]'
grep_without_c_comments "$EXPR" $CJGFILES |
	filter_quotes

unset EXPR
unset EXCLEXPR
echo

echo '---------- [!|~] something ----------'
echo
git grep -P '[!~] \b' -- $FILES
echo

echo '---------- - FIX* ----------'
echo
git grep -P '(\(|, )\- FIX' -- $FILES
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT OPERATOR CONTINUANCE **********'
echo
OP='([=\+\-\*/%&\|\^\!\<\>]*=|[\+\-\*/%]|\>+|\<+|&+|\|+|\^|\?|\:)'
EXPR='^ *'"$OP"' +'
git grep -P "$EXPR" -- $FILES $NCJGFILES ':!*.md'
EXPR='^ *'"$OP"' +'
grep_without_c_comments "$EXPR" $CJGFILES
unset EXPR
echo

echo # ************************************************************************


echo '********** DETECTING INCORRECT FUNCTION SPACING **********'
echo
EXPR='\b \([^\*]'
git grep -P "$EXPR" -- $FILES $NCJGFILES ':!*.md' ':!CMakeLists.txt' ':!cmakescripts/'
# Process C and GAS files separately, so we can parse out the comments
EXCLEXPR='(?<!if \(.)(?<!return \(.)(?<!for \(.)(?<!while \(.)(?<!switch \(.)(?<!else \(.)(?<!\.short \(.)(?<!catch \(.)(?<!do \(.)'
grep_without_c_comments "$EXPR""$EXCLEXPR" $CJGFILES |
	filter_quotes
echo

echo # ************************************************************************


if [ "$1" = "-selftest" ]; then
	popd >/dev/null 2>&1
fi
